---
spring:
  profiles: client-subject
words: I,You,He,She,It
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: ${PORT:${SERVER_PORT:0}}

---
spring:
  profiles: client-article
words: a,the
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: ${PORT:${SERVER_PORT:0}}
  
---
spring:
  profiles: client-adjective
words: reasonable,leaky,suspicious,ordinary,unli
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/kely
server:
  port: ${PORT:${SERVER_PORT:0}}
  
---
spring:
  profiles: client-noun
words: boat,book,vote,seat,backpack,partition,groundhog  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: ${PORT:${SERVER_PORT:0}}
