eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8877/eureka/
server:
  port: ${PORT:${SERVER_PORT:0}}
        
---
spring:
  profiles: client-subject
words: I,You,He,She,It

---
spring:
  profiles: client-verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: client-article
words: a,the

---
spring:
  profiles: client-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: client-noun
words: boat,book,vote,seat,backpack,partition,groundhog  
